startuml

abstract class Vehiculo {
    # placa: int
    # marca: String
    # velocidadMaxima: Double
    
    + Vehiculo(placa: int, marca: String, velocidadMaxima: Double)
    {abstract} + mover()
    {abstract} + calcularPeaje(): Double
}

class Auto {
    - numeroPuertas: int
    
    + Auto(placa: int, marca: String, velocidadMaxima: Double, numeroPuertas: int)
    + mover()
    + calcularPeaje(): Double
}

class Moto {
    - tipo: TipoMoto
    
    + Moto(placa: int, marca: String, velocidadMaxima: Double, tipo: TipoMoto)
    + mover()
    + calcularPeaje(): Double
    + getTipo(): TipoMoto
}

class Camion {
    - capacidadCarga: Double
    
    + Camion(placa: int, marca: String, velocidadMaxima: Double, capacidadCarga: Double)
    + mover()
    + calcularPeaje(): Double
}

enum TipoMoto {
    DEPORTIVA
    CRUISER
    SCOOTER
}

' Relaciones
Moto "1" *-- "1" TipoMoto
Vehiculo <|-- Auto
Vehiculo <|-- Moto
Vehiculo <|-- Camion

@enduml
